INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Akila','Supun');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Gayan','Chanaka');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Prihan','Senanayake');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Ajith','Sugunasiri');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Shehan','wijesinghe');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Suneth','Priyanga');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME) VALUES ('Kamal','Thilakarathne');